FROM python:3.6
RUN pip3 install \
    jupyterhub==0.7.2 \
    'notebook>=5.0,<=6.0'

RUN pip3 install matplotlib
RUN pip3 install control
RUN pip3 install numpy
RUN pip3 install sympy
RUN pip3 install ipywidgets

# create a user, since we don't want to run as root
RUN useradd -m ee3011
ENV HOME=/home/ee3011
WORKDIR $HOME
USER ee3011

RUN git clone https://github.com/yilinmo/EE3011.git
CMD ["jupyterhub-singleuser"]

